### ISSUE TITLE
Discussion : Storage And Persistance

### ISSUE THREAD

**Issue by youknowriad** [jubianchi/neutron#3]
I've two concerns about storage and persistance of app releases : 

A nice feature I think is to have the ability to manage the updates by API : 
 - Creating new application
 - Uploading a new release for an application
 - Having the possibility to store the application's zip file in a cloud storage provider (somehow a different feature)

To accomplish this, I think we should consider using a tiny embed database (I'm not familiar about the different possibilities in node, this https://github.com/louischatriot/nedb/ could be a nice pick).

My second concern is about the heroku readiness of the server : 

Heroku use a temporary file system not persisted between app restarts, so event If our database is tiny and persisted to a local tiny file, the file is dropped on app restart, so may be we could provide a way to configure a cloud provider to persist this database ? (may be this should be done in a second time).

What do you think about this ?

**Comment by jubianchi** [comment]
My concerns here are the following:

* Using a database of any kind seems good, 
* But I'm afraid of the complexity it would introduce,
* Migration should be kept as simple as possible (today, I upload updates on S3 but I want to move everything to Azure for example)

There are probably other points I forget here...

My thoughts are the following if we choose to use a database:

* Store **everything** in the DB (applications, releases, updates BLOB, changelog, ...)
* Use a storage provider only to host the database file

What we have to check is:

* the database must allow storing BLOBs
* it is file based so that migration is easy (a single file to move from/to storage providers)
* it does not require a service to be up to keep deployment as simple as possible (a signle docker container or a single dyno on heroku)
